# Generated by Django 5.0.7 on 2024-07-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='user',
        ),
    ]
