# Generated by Django 5.1.4 on 2025-02-21 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productimage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique rating',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_rating'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.order'),
        ),
    ]
