# Generated by Django 5.1.3 on 2025-02-26 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_payment_remove_rating_unique_rating_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='category_slug_index'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['order', 'product'], name='order_product_index'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payment_order_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_slug_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_categories_index'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['product'], name='product_rating_index'),
        ),
    ]
