# Generated by Django 5.0.7 on 2024-07-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('store', '0004_alter_category_cover_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
