# Generated by Django 5.0.7 on 2024-07-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_user_remove_orderitem_order_and_more'),
        ('payment', '0002_alter_paymentorder_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
